name: Deploy App & Server and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build & deploy via vercel
        working-directory: ./app
        run: |-
          yarn

          echo ${{ secrets.APP_ENV_CONTENT }} | base64 -d > .env.local
          echo ${{ secrets.APP_GOOGLE_SERVICE_ACCOUNT_CONTENT }} | base64 -d > google-service-account.json

          mkdir .vercel
          echo '{ "projectId": "${{ secrets.VERCEL_PROJECT_ID }}", "orgId": "${{ secrets.VERCEL_ORG_ID}}" }' \
            > .vercel/project.json

          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          SENTRY_URL: '${{ secrets.SENTRY_URL }}'
          SENTRY_ORG: '${{ secrets.SENTRY_ORG }}'
          SENTRY_PROJECT: '${{ secrets.APP_SENTRY_PROJECT }}'
          SENTRY_AUTH_TOKEN: '${{ secrets.SENTRY_AUTH_TOKEN }}'
          SENTRY_ENVIRONMENT: 'production'
          SENTRY_LOG_LEVEL: 'DEBUG'

  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Publish packages
        run: |-
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc

          git config --global user.email "hello@julianburr.de"
          git config --global user.name "Julian Burr"

          yarn
          yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
