name: Deploy App & Server and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: app

      - name: Build & deploy via vercel
        if: steps.changed.outputs.changed == 'true'
        working-directory: ./app
        run: |-
          yarn

          mkdir .vercel
          echo '{ "projectId": "${{ secrets.VERCEL_PROJECT_ID }}", "orgId": "${{ secrets.VERCEL_ORG_ID}}" }' \
            > .vercel/project.json

          echo ${{ secrets.APP_ENV_CONTENT }} | base64 -d > .env.local
          echo ${{ secrets.APP_GOOGLE_SERVICE_ACCOUNT_CONTENT }} | base64 -d > .env.local

          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: packages
      
      - name: Publish packages
        if: steps.changed.outputs.changed == 'true'
        run: |-
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc

          git config --global user.email "hello@julianburr.de"
          git config --global user.name "Julian Burr"

          yarn
          yarn release:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
