name: "Cron Daily"

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run_cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Subscriptions cleanup
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://www.lightkeepr.io/api/cleanup/subscriptions"
          method: "POST"
          bearerToken: ${{ secrets.BEARER_TOKEN }}
          timeout: 30000

      - name: Records cleanup
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://www.lightkeepr.io/api/cleanup/records"
          method: "POST"
          bearerToken: ${{ secrets.BEARER_TOKEN }}
          timeout: 30000
