name: Deploy App & Server and Publish Packages

on:
  push:
    branches:
      - main

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: app

      - name: Build & deploy via vercel
        if: steps.changed.outputs.changed == 'true'
        run: |-
          cat .github/configs/main_env.ts > app/src/env.ts
          cd app

          yarn
          yarn build

          mkdir .vercel
          echo '{ "projectId": "${{ secrets.VERCEL_PROJECT_ID }}", "orgId": "${{ secrets.VERCEL_ORG_ID}}" }' \
            > .vercel/project.json

          vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: server

      - name: Deploy via vercel
        if: steps.changed.outputs.changed == 'true'
        run: |-
          echo '${{ secrets.FIREBASE_SERVER_SECRET }}' > server/firebase-secret.json
          cd server

          yarn

          mkdir .vercel
          echo '{ "projectId": "${{ secrets.SERVER_VERCEL_PROJECT_ID }}", "orgId": "${{ secrets.SERVER_VERCEL_ORG_ID}}" }' \
            > .vercel/project.json

          GOOGLE_APPLICATION_CREDENTIALS=./firebase-secret.json vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

  publish_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: packages
      
      - name: Publish packages
        if: steps.changed.outputs.changed == 'true'
        run: |-
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc

          git config --global user.email "hello@julianburr.de"
          git config --global user.name "Julian Burr"

          yarn
          yarn release:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
