name: Deploy App Staging (PR)

on:
  pull_request:
    paths:
      - app/**

jobs:
  deploy_app_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout GitHub Actions Repo
        uses: actions/checkout@v2
        with:
          repository: julianburr/github-actions
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .github/actions/custom-actions

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Use node modules from cache if available
        uses: ./.github/actions/custom-actions/cache-node-modules

      - name: Install dependencies
        run: |-
          yarn

      - name: Linting and typechecks
        working-directory: ./app
        run: |-
          yarn lint --quiet
          yarn typecheck

      - name: Create Google Service Account File
        working-directory: ./app
        run: |-
          echo ${{ secrets.APP_GOOGLE_SERVICE_ACCOUNT_CONTENT }} | base64 -d > google-service-account.json

      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          directory: ./app
          envkey_NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          envkey_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          envkey_NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          envkey_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          envkey_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          envkey_NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          envkey_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          envkey_NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}

      - name: Deploy via Vercel
        uses: ./.github/actions/custom-actions/deploy-vercel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-token: ${{ secrets.VERCEL_TOKEN}}
          is-production: false
          add-comment: true
