name: Publish Packages Canary (PR)

on:
  pull_request:
    paths:
      - packages/**

jobs:
  publish_packages_canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Use node modules from cache if available
        uses: ./.github/actions/custom-actions/cache-node-modules

      - name: Install dependencies
        run: |-
          yarn

      - name: Linting and typechecks
        working-directory: ./packages
        run: |-
          yarn lint --quiet
          yarn typecheck

      - name: Publish packages
        run: |-
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          yarn --cwd=./packages build
          yarn release:canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
